# $Id$

=head1 General

This package provides an CSV-based import/export backend for customer company items.

This package automatically creates import-/export mapping during re-/installation for each registered customer company backend as long as no equally named mapping exists.

=over 4 

=item * "Default Validity"

=over 8

if no valid information is provided in import data, this valid information is used

=back

=back

The field "CustomerID" is automatically used as identifier for existing entries: If a CustomerCompany with the given CustomerID already exists it will be updated. Otherwise a new CustomerCompany will be created.


This software comes with ABSOLUTELY NO WARRANTY. For details, see the enclosed file COPYING for license information (AGPL). If you did not receive this file, see http://www.gnu.org/licenses/agpl.txt.

=cut
