# $Id$

=head1 General

This package provides an CSV-based import/export backend for user (with custom queues, roles and some preferences).

This package automatically creates import-/export mapping during re-/installation for each registered user.

=over 4

=item * "Default Email"

        default email address if not specified in import data

=item * "Default Password-Suffix"

        a password will be identical with the login followed by this suffix if not specified in import data

=item * "Max. number of Custom Queues

        specifies how many custom queues might be imported or exported (number of columns)

=item * "Max. number of roles"

        specifies how many roles might be imported or exported (number of columns)

=item * "Default Validity"

        if no valid information is provided in import data, this valid information is used

=back

=head1 COPYRIGHT

Copyright (C) 2006-2013 c.a.p.e. IT GmbH, http://www.cape-it.de/

The following persons have contributed to this extension:

=over 4

=item * Ricky(dot)Kaiser(at)cape(dash)it(dot)de

=item * Frank(dot)Oberender(at)cape(dash)it(dot)de

=item * Torsten(dot)Thau(at)cape(dash)it(dot)de

=back

This software comes with ABSOLUTELY NO WARRANTY. For details, see the enclosed file LICENSE for license information (AGPL). If you did not receive this file, see http://www.gnu.org/licenses/agpl.txt.

=cut
